### ISSUE TITLE
Ratelimit on Unauthenticated Github API Calls

### ISSUE THREAD

**Issue by jpoehnelt** [justinwp/contributions#2]
The limit is 60/hour for unauthenticated and 5000/hour for authenticated. Probably need to use oauth for requests or a throwaway account with basic authentication. 

[Python Requests Authentication](http://docs.python-requests.org/en/latest/user/authentication/)

**Comment by shariq1989** [comment]
closed in commit e1bf55e1e2ef5bcf2c17934230c920b58dc032aa
